In [1]:
import pandas as pd
import numpy as np

### Import Dataset

In [2]:
final_events_1 = pd.read_json("data_json/final_events_1.json")
final_events_2 = pd.read_json("data_json/final_events_2.json")

In [3]:
final_events_1

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game,...,Title(s),Other_names,Nationality,Original_name,Name_order,event,team,position,medal,Events
0,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,None,None,None,None,None,"Singles, Men(Olympic)",,=17,,NaN
1,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,None,None,None,None,None,"Doubles, Men(Olympic)",Jean Montariol,DNS,,NaN
2,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,"Singles, Men(Olympic)",,=32,,NaN
3,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,"Doubles, Mixed(Olympic)",Jeanne Vaussard,=8,,NaN
4,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,"Doubles, Men(Olympic)",Jacques Brugnon,4,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153443,73859,None,Competed in Olympic Games,Male,"Johannes Michaël ""Jan""•Meijer",Jan•Meijer,"8 June 1921 in Amsterdam, Noord-Holland (NED)","21 October 1993 in Amsterdam, Noord-Holland (NED)",Netherlands,1948 Summer Olympics,...,None,None,None,None,None,"100 metres, Men(Olympic)",,3 h4 r1/4,,NaN
153444,73859,None,Competed in Olympic Games,Male,"Johannes Michaël ""Jan""•Meijer",Jan•Meijer,"8 June 1921 in Amsterdam, Noord-Holland (NED)","21 October 1993 in Amsterdam, Noord-Holland (NED)",Netherlands,1948 Summer Olympics,...,None,None,None,None,None,"4 × 100 metres Relay, Men(Olympic)",Netherlands,6,,NaN
153445,73860,https://d2a3o6pzho379u.cloudfront.net/73860.jpg,Competed in Olympic Games,Male,Emiel Remco•Mellaard,Emiel•Mellaard,"21 March 1966 in Spijkenisse, Zuid-Holland (NED)",None,Netherlands,1988 Summer Olympics,...,None,None,None,None,None,"Long Jump, Men(Olympic)",,11,,NaN
153446,73861,None,Competed in Olympic Games,Male,Menso Johannes•Menso,Menso•Menso,"14 April 1903 in Den Haag (The Hague), Zuid-Ho...","26 April 1990 in Amsterdam, Noord-Holland (NED)",Netherlands,1924 Summer Olympics,...,None,None,None,None,None,"400 metres, Men(Olympic)",,4 h9 r1/4,,NaN
153447,73861,None,Competed in Olympic Games,Male,Menso Johannes•Menso,Menso•Menso,"14 April 1903 in Den Haag (The Hague), Zuid-Ho...","26 April 1990 in Amsterdam, Noord-Holland (NED)",Netherlands,1924 Summer Olympics,...,None,None,None,None,None,"800 metres, Men(Olympic)",,5 h6 r1/3,,NaN

In [21]:
final_events_2

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game,...,Title(s),Other_names,Nationality,Original_name,Name_order,event,team,position,medal,Events
0,73861,None,Competed in Olympic Games,Male,Menso Johannes•Menso,Menso•Menso,"14 April 1903 in Den Haag (The Hague), Zuid-Ho...","26 April 1990 in Amsterdam, Noord-Holland (NED)",Netherlands,1924 Summer Olympics,...,None,None,None,None,None,"4 × 400 metres Relay, Men(Olympic)",Netherlands,DNS,,NaN
1,73862,https://d2a3o6pzho379u.cloudfront.net/73862.jpg,Competed in Olympic Games,Male,"Gerardus Hermanus Maria ""Gerard""•Nijboer",Gerard•Nijboer,"18 August 1955 in Hasselt, Overijssel (NED)",None,Netherlands,1980 Summer Olympics,...,None,None,None,None,None,"Marathon, Men(Olympic)",,2,Silver,NaN
2,73862,https://d2a3o6pzho379u.cloudfront.net/73862.jpg,Competed in Olympic Games,Male,"Gerardus Hermanus Maria ""Gerard""•Nijboer",Gerard•Nijboer,"18 August 1955 in Hasselt, Overijssel (NED)",None,Netherlands,1984 Summer Olympics,...,None,None,None,None,None,"Marathon, Men(Olympic)",,DNF,,NaN
3,73862,https://d2a3o6pzho379u.cloudfront.net/73862.jpg,Competed in Olympic Games,Male,"Gerardus Hermanus Maria ""Gerard""•Nijboer",Gerard•Nijboer,"18 August 1955 in Hasselt, Overijssel (NED)",None,Netherlands,1988 Summer Olympics,...,None,None,None,None,None,"Marathon, Men(Olympic)",,13,,NaN
4,73863,https://d2a3o6pzho379u.cloudfront.net/73863.jpg,Competed in Olympic Games,Male,"Martinus Bernardus ""Tinus""•Osendarp",Tinus•Osendarp,"21 May 1916 in Delft, Zuid-Holland (NED)","20 June 2002 in Heerlen, Limburg (NED)",Netherlands,1936 Summer Olympics,...,None,None,None,None,None,"100 metres, Men(Olympic)",,3,Bronze,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153443,149222,None,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",None,ROC,2022 Winter Olympics,...,None,None,None,None,None,"Ice Hockey, Women(Olympic)",ROC,5,,NaN
153444,149223,None,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",None,ROC,2022 Winter Olympics,...,None,None,None,Валерия Сергеевна•Меркушева,None,"Ice Hockey, Women(Olympic)",ROC,5,,NaN
153445,149224,None,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",None,ROC,2022 Winter Olympics,...,None,None,None,Юлия•Смирнова,None,"Ice Hockey, Women(Olympic)",ROC,5,,NaN
153446,149225,https://d2a3o6pzho379u.cloudfront.net/149225.jpg,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,1924 Summer Olympics,...,None,None,None,None,None,"400 metres Hurdles, Men(Olympic)",,5 h5 r1/3,,NaN
153447,149814,None,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,1948 Summer Olympics,...,None,None,None,None,None,"Water Polo, Men(Olympic)",Australia,DNS,,NaN

#### Concat the dataframe

In [22]:
final_events_concat = pd.concat([final_events_1, final_events_2], ignore_index=True, sort=False).drop(columns=["Events"])

In [23]:
final_events_concat

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game,...,Nick/petnames,Title(s),Other_names,Nationality,Original_name,Name_order,event,team,position,medal
0,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,None,None,None,None,None,None,"Singles, Men(Olympic)",,=17,
1,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,None,None,None,None,None,None,"Doubles, Men(Olympic)",Jean Montariol,DNS,
2,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,None,"Singles, Men(Olympic)",,=32,
3,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,None,"Doubles, Mixed(Olympic)",Jeanne Vaussard,=8,
4,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,None,None,None,None,None,None,"Doubles, Men(Olympic)",Jacques Brugnon,4,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306891,149222,None,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",None,ROC,2022 Winter Olympics,...,None,None,None,None,None,None,"Ice Hockey, Women(Olympic)",ROC,5,
306892,149223,None,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",None,ROC,2022 Winter Olympics,...,None,None,None,None,Валерия Сергеевна•Меркушева,None,"Ice Hockey, Women(Olympic)",ROC,5,
306893,149224,None,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",None,ROC,2022 Winter Olympics,...,None,None,None,None,Юлия•Смирнова,None,"Ice Hockey, Women(Olympic)",ROC,5,
306894,149225,https://d2a3o6pzho379u.cloudfront.net/149225.jpg,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,1924 Summer Olympics,...,None,None,None,None,None,None,"400 metres Hurdles, Men(Olympic)",,5 h5 r1/3,
306895,149814,None,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,1948 Summer Olympics,...,None,None,None,None,None,None,"Water Polo, Men(Olympic)",Australia,DNS,

In [24]:
final_events_concat.iloc[:, :15]

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game,discipline,noc,Measurements,Affiliations,Nick/petnames
0,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,Tennis,FRA,None,None,None
1,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,Tennis,FRA,None,None,None
2,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,Tennis,FRA,None,None,None
3,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,Tennis,FRA,None,None,None
4,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,Tennis,FRA,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306891,149222,None,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",None,ROC,2022 Winter Olympics,Ice Hockey (Ice Hockey),ROC,167 cm / 61 kg,"Agidel, Ufa (RUS)",None
306892,149223,None,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",None,ROC,2022 Winter Olympics,Ice Hockey (Ice Hockey),ROC,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",None
306893,149224,None,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",None,ROC,2022 Winter Olympics,Ice Hockey (Ice Hockey),ROC,163 cm / 55 kg,"Agidel, Ufa (RUS)",None
306894,149225,https://d2a3o6pzho379u.cloudfront.net/149225.jpg,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,1924 Summer Olympics,Athletics,FRA,166 cm,"Beauvoisine FC, Rouen (FRA)",None
306895,149814,None,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,1948 Summer Olympics,Water Polo (Aquatics),AUS,None,None,None

#### Save to CSV

In [25]:
# final_events_concat.to_csv("events.csv", sep=";", index=False)

### Data Cleaning

In [4]:
events = pd.read_csv("data_csv/events.csv", sep=";",low_memory=False)

In [5]:
events.iloc[:, :10]

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game
0,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics
1,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics
2,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics
3,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics
4,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics
...,...,...,...,...,...,...,...,...,...,...
306891,149222,NaN,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,2022 Winter Olympics
306892,149223,NaN,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,2022 Winter Olympics
306893,149224,NaN,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,2022 Winter Olympics
306894,149225,https://d2a3o6pzho379u.cloudfront.net/149225.jpg,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,1924 Summer Olympics
306895,149814,NaN,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,1948 Summer Olympics

In [6]:
events.isnull().sum()

id                    0
photo_link        63484
Roles                 0
Sex                   0
Full_name             0
Used_name             0
Born               2537
Died             234237
NOC                   0
game               2394
discipline            0
noc                   0
Measurements      69058
Affiliations      93017
Nick/petnames    283832
Title(s)         305896
Other_names      290923
Nationality      288143
Original_name    243532
Name_order       291283
event                95
team             186913
position             95
medal            262728
dtype: int64

There are blank values in the medal column

In [7]:
events.medal.value_counts()

medal
Bronze    14808
Gold      14790
Silver    14570
Name: count, dtype: int64

Need to extract the Year and the Type of Olympics from the game column

In [8]:
events.game.value_counts()

game
2000 Summer Olympics            13869
1996 Summer Olympics            13833
2020 Summer Olympics            13828
2016 Summer Olympics            13732
2008 Summer Olympics            13695
                                ...
2012 Winter Youth Olympics        330
1956 Equestrian Olympics          300
2016 Winter Youth Olympics        245
2018 Summer Youth Olympics         47
1888-89 Zappas Olympic Games        1
Name: count, Length: 62, dtype: int64

NOCs

In [31]:
events.NOC.value_counts()

NOC
United States                     21213
France                            14029
Great Britain                     13061
Italy                             12044
Canada                            11320
                                  ...
Kingdom of Saudi Arabia  Libya        1
France  Monaco                        1
Finland  Switzerland                  1
Czechoslovakia  Finland               1
Canada  Sweden                        1
Name: count, Length: 696, dtype: int64

In [32]:
events.NOC.value_counts()[:30]

NOC
United States                 21213
France                        14029
Great Britain                 13061
Italy                         12044
Canada                        11320
Germany                       10068
Japan                          9845
Sweden                         9267
Australia                      8532
Hungary                        7259
Switzerland                    7000
Poland                         6796
People's Republic of China     6369
Netherlands                    6290
Finland                        6112
Spain                          5879
Norway                         5721
Austria                        5681
Republic of Korea              5297
Soviet Union                   5231
Romania                        4748
Brazil                         4451
Russian Federation             4397
Belgium                        4146
Czechoslovakia                 4078
Denmark                        3820
Bulgaria                       3733
Argentina                      3703
Greece                         3571
Mexico                         3180
Name: count, dtype: int64

Rename the columns

In [33]:
events.columns

Index(['id', 'photo_link', 'Roles', 'Sex', 'Full_name', 'Used_name', 'Born',
       'Died', 'NOC', 'game', 'discipline', 'noc', 'Measurements',
       'Affiliations', 'Nick/petnames', 'Title(s)', 'Other_names',
       'Nationality', 'Original_name', 'Name_order', 'event', 'team',
       'position', 'medal'],
      dtype='object')

In [9]:
events["medal"] = events["medal"].fillna(np.nan)

In [10]:
events["medal"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
306891    NaN
306892    NaN
306893    NaN
306894    NaN
306895    NaN
Name: medal, Length: 306896, dtype: object

In [11]:
events.medal.value_counts()

medal
Bronze    14808
Gold      14790
Silver    14570
Name: count, dtype: int64

In [12]:
events["year"] = events["game"].apply(lambda x: str(x).split()[0])

In [13]:
events

,id,photo_link,Roles,Sex,Full_name,Used_name,Born,Died,NOC,game,...,Title(s),Other_names,Nationality,Original_name,Name_order,event,team,position,medal,year
0,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Singles, Men(Olympic)",NaN,=17,NaN,1912
1,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1912 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Doubles, Men(Olympic)",Jean Montariol,DNS,NaN,1912
2,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Singles, Men(Olympic)",NaN,=32,NaN,1920
3,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Doubles, Mixed(Olympic)",Jeanne Vaussard,=8,NaN,1920
4,1,https://d2a3o6pzho379u.cloudfront.net/1.jpg,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1920 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Doubles, Men(Olympic)",Jacques Brugnon,4,NaN,1920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306891,149222,NaN,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,2022 Winter Olympics,...,NaN,NaN,NaN,NaN,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022
306892,149223,NaN,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,2022 Winter Olympics,...,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022
306893,149224,NaN,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,2022 Winter Olympics,...,NaN,NaN,NaN,Юлия•Смирнова,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022
306894,149225,https://d2a3o6pzho379u.cloudfront.net/149225.jpg,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,1924 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"400 metres Hurdles, Men(Olympic)",NaN,5 h5 r1/3,NaN,1924
306895,149814,NaN,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,1948 Summer Olympics,...,NaN,NaN,NaN,NaN,NaN,"Water Polo, Men(Olympic)",Australia,DNS,NaN,1948

In [14]:
events["season"] = events["game"].apply(lambda x: " ".join(str(x).split()[1:-1]) if len(str(x).split()[1:]) > 0 else np.nan)

In [40]:
# events["season"]= events["season"].apply(lambda x: x[0] if len(x) > 0 else np.nan)

In [15]:
events.season.value_counts()

season
Summer            237254
Winter             59320
Winter Youth        4191
Intercalated        2037
Summer Youth        1399
Equestrian           300
Zappas Olympic         1
Name: count, dtype: int64

In [16]:
events.year.value_counts()

year
2020       17444
1992       16541
1988       15116
2016       13977
2000       13869
1996       13833
2008       13695
2004       13540
2012       13315
1972       12226
1984       11897
1968       10818
1976       10797
1964        9673
1952        9652
1960        9469
1980        9142
1948        7235
1936        6814
1956        6683
1924        5836
2014        5535
2010        5190
2018        5186
1928        5083
2022        5006
1912        4602
2006        4426
1920        4382
2002        4140
1998        3680
1908        3557
1994        3203
1932        2502
nan         2394
1900        2241
1906        2037
1904        1775
1896         384
1888-89        1
Name: count, dtype: int64

In [17]:
events.season.isna().sum()

2394

In [20]:
events.iloc[:, 10:]

,discipline,noc,Measurements,Affiliations,Nick/petnames,Title(s),Other_names,Nationality,Original_name,Name_order,event,team,position,medal,year,season
0,Tennis,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Singles, Men(Olympic)",NaN,=17,NaN,1912,Summer
1,Tennis,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Doubles, Men(Olympic)",Jean Montariol,DNS,NaN,1912,Summer
2,Tennis,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Singles, Men(Olympic)",NaN,=32,NaN,1920,Summer
3,Tennis,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Doubles, Mixed(Olympic)",Jeanne Vaussard,=8,NaN,1920,Summer
4,Tennis,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Doubles, Men(Olympic)",Jacques Brugnon,4,NaN,1920,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306891,Ice Hockey (Ice Hockey),ROC,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022,Winter
306892,Ice Hockey (Ice Hockey),ROC,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022,Winter
306893,Ice Hockey (Ice Hockey),ROC,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,"Ice Hockey, Women(Olympic)",ROC,5,NaN,2022,Winter
306894,Athletics,FRA,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,"400 metres Hurdles, Men(Olympic)",NaN,5 h5 r1/3,NaN,1924,Summer
306895,Water Polo (Aquatics),AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Water Polo, Men(Olympic)",Australia,DNS,NaN,1948,Summer

In [21]:
events.to_csv("data_csv/events_cleaned.csv", sep=";", index=False)